# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a54af002ea4f3d05dbf78d842a4771f6d314a4ac8e7bf507a29a666be697224b67fa644cd98563ea4c73ad89bebb3c94e379be42e9104acd82e26cdcc4129f7b

test:
  secret_key_base: 622fbe5f27a710e221e535fe67551ef7cf39759e408a6854dc4d621afd8e8a5f8859e8938c5532d61cef777a9f2d6dc6b7dcae70ed9e0739e9656e7abcadf90d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
